import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { env } from 'cloudflare:workers';
import {
  createMessageBatch,
  createScheduledController,
  createExecutionContext,
  getQueueResult,
  runInDurableObject,
  waitOnExecutionContext,
} from 'cloudflare:test';
import { eq } from 'drizzle-orm';
import { getDb } from '../../src/db/client';
import { leads } from '../../src/db/schema';
import { STUCK_ROW_THRESHOLD_MINUTES } from '../../src/lib/triage-config';
import type { LeadTriageAgent } from '../../src/agents/lead-triage-agent';
import type { Env, TriageMessage } from '../../src/types';
import type { ExecutionContext, MessageBatch } from '@cloudflare/workers-types';

// src/worker.ts pulls @astrojs/cloudflare/entrypoints/server (which references
// the virtual `astro-cloudflare:config` only generated by `astro build`). Stub
// it so the worker module loads in tests. The fetch handler delegates to this
// for non-/agents requests; tests assert the gate behavior, not the delegate.
vi.mock('@astrojs/cloudflare/entrypoints/server', () => ({
  default: {
    fetch: async () => new Response('astro-stub', { status: 200 }),
  },
}));

const { workosState } = vi.hoisted(() => ({
  workosState: { authenticated: true, refreshable: true },
}));

vi.mock('@workos-inc/node', () => ({
  WorkOS: class {
    userManagement = {
      loadSealedSession: () => ({
        authenticate: async () =>
          workosState.authenticated
            ? {
                authenticated: true,
                user: { id: 'u', email: 'tester@example.com' },
              }
            : { authenticated: false },
        refresh: async () => ({ authenticated: false }),
      }),
    };
  },
}));

vi.mock('ai', async () => {
  const { mockWorkersAI } = await import('../mocks/workers-ai');
  return {
    generateText: mockWorkersAI({
      classify: { category: 'consulting-fit', confidence: 0.9, reasoning: 'fits' },
      qualify: {
        industry: 'cpa',
        geography: 'fort-worth',
        size_signal: 'small-2-10',
        problem_shape: 'review-queue',
        urgency_signal: 'in-pain',
      },
      draft: 'Reply draft body for tests.',
    }).generateText,
  };
});

import worker from '../../src/worker';

beforeEach(async () => {
  workosState.authenticated = true;
  await runInDurableObject(
    env.LEAD_TRIAGE_AGENT.get(env.LEAD_TRIAGE_AGENT.idFromName('global')),
    async (instance: LeadTriageAgent) => {
      await instance.onStart();
      instance.sql`DELETE FROM agent_activity`;
    },
  );
});

afterEach(() => {
  vi.restoreAllMocks();
});

describe('worker.fetch agent-path gate', () => {
  it('returns 401 when /agents/* is hit without a session cookie', async () => {
    const req = new Request('https://test/agents/lead-triage-agent/global');
    const ctx = createExecutionContext();
    const res = await worker.fetch(req, env, ctx);
    await waitOnExecutionContext(ctx);
    expect(res.status).toBe(401);
  });

  it('delegates non-/agents requests to the Astro server stub', async () => {
    const req = new Request('https://test/about');
    const ctx = createExecutionContext();
    const res = await worker.fetch(req, env, ctx);
    await waitOnExecutionContext(ctx);
    expect(res.status).toBe(200);
    expect(await res.text()).toBe('astro-stub');
  });
});

describe('worker.queue handler', () => {
  it('acks each message after dispatching to the agent', async () => {
    const db = getDb(env.LEADS_DB);
    await db.insert(leads).values({
      id: 'L_QUEUE_OK',
      submittedAt: new Date().toISOString(),
      name: 'A',
      email: 'a@b',
      message: 'A real message that triggers the workflow.',
      userAgent: null,
      source: 'test',
    });

    const batch = createMessageBatch<TriageMessage>('lead-triage', [
      { id: '1', timestamp: new Date(), attempts: 0, body: { leadId: 'L_QUEUE_OK' } },
    ]);
    // src/worker.ts:queue's TS signature is (batch, env). Workers runtime
    // passes a third ctx arg that the handler ignores; pool-workers uses
    // ctx to track ack/retry. Cast through unknown to call with all three.
    const ctx = createExecutionContext();
    type QueueWithCtx = (
      b: MessageBatch<TriageMessage>,
      e: Env,
      c: ExecutionContext,
    ) => Promise<void>;
    await (worker.queue as unknown as QueueWithCtx)(batch, env, ctx);
    await waitOnExecutionContext(ctx);

    const result = await getQueueResult(batch, ctx);
    // ack on success: zero pending retries, all messages explicitly ack'd.
    expect(result.retryMessages).toHaveLength(0);
    expect(result.explicitAcks).toContain('1');
  });

  it('retries when agent.queueLead throws synchronously', async () => {
    const stub = env.LEAD_TRIAGE_AGENT.get(env.LEAD_TRIAGE_AGENT.idFromName('global'));
    // Force a synchronous throw from queueLead so the handler hits its
    // catch branch and calls msg.retry. Spy on the stub method.
    vi.spyOn(stub, 'queueLead').mockRejectedValueOnce(new Error('boom'));
    // Re-bind: our test-worker fetches a fresh stub each invocation, so we
    // need to spy on the namespace's get() to return our spied stub.
    vi.spyOn(env.LEAD_TRIAGE_AGENT, 'get').mockReturnValue(stub);

    const batch = createMessageBatch<TriageMessage>('lead-triage', [
      { id: '2', timestamp: new Date(), attempts: 0, body: { leadId: 'L_RETRY' } },
    ]);
    const ctx = createExecutionContext();
    type QueueWithCtx = (
      b: MessageBatch<TriageMessage>,
      e: Env,
      c: ExecutionContext,
    ) => Promise<void>;
    await (worker.queue as unknown as QueueWithCtx)(batch, env, ctx);
    await waitOnExecutionContext(ctx);

    const result = await getQueueResult(batch, ctx);
    expect(result.retryMessages.length).toBeGreaterThan(0);
    expect(result.retryMessages[0].msgId).toBe('2');
  });

});

describe('worker.scheduled handler', () => {
  it('invokes sweepStuckRows so stale processing rows reset to pending', async () => {
    const db = getDb(env.LEADS_DB);
    const stale = new Date(Date.now() - (STUCK_ROW_THRESHOLD_MINUTES + 5) * 60 * 1000).toISOString();
    await db.insert(leads).values({
      id: 'L_CRON_STALE',
      submittedAt: stale,
      name: 'A',
      email: 'a@b',
      message: 'Stale processing row for cron sweep test.',
      userAgent: null,
      source: 'test',
      status: 'processing',
    });
    await db.update(leads).set({ updatedAt: stale }).where(eq(leads.id, 'L_CRON_STALE'));

    const controller = createScheduledController({ cron: '*/5 * * * *' });
    // src/worker.ts:scheduled is declared with (controller, env) — no ctx.
    await worker.scheduled(controller, env);

    const [row] = await db.select().from(leads).where(eq(leads.id, 'L_CRON_STALE')).limit(1);
    expect(row?.status).toBe('pending');
  });
});
